### ISSUE TITLE
GIT Setup (2)

### ISSUE THREAD

**Issue by mmoollllee** [codecampleipzig/communic#10]
#### Story

As __developers__, we want __a repository__, in order __to work together like pros__.

#### Acceptance Criteria

- [x] Setup Repo
- [x] Write Readme & Guidelines

**Comment by mmoollllee** [comment]
Gabe & Simon stole this task... But I still want the points!

Here is the Readme I came up with:

> # LsdCommunitio
> 
> We want to build a Minimum Vaiable Product of a Community Software which helps Community Leaders and Community Members communicating with interessted people.
> 
> This repo holds the sprints by Team LSD. Maybe there will be a repo for all Teams together by Code Camp to replace this repository.
> 
> ## Official Goal
> 
> A Hybrid community needs an engaging and motivating way to plan and build projects that are proposed by initiators and users who actively contribute.
> 
> ## Getting Started
> 
> ### Branches
> As we develop this app with SCRUM, there should be a branch for every User Story (task) that should be named with the sprint number.
> So a branch could be called `tasklistTemplate-01` where `01` is the first sprint.
> 
> This branch get's merged into the `sprint-01` as soon as it was reviewed and aproved.
> 
> After every sprint we merge the `sprint-xx` branch into master.
> 
> ### Angular
> 
> Run `ng serve` for a dev server. Navigate to `http://localhost:4200/`. The app will automatically reload if you change any of the source files.
> 
> ## Code scaffolding
> 
> Run `ng generate component component-name` to generate a new component. You can also use `ng generate directive|pipe|service|class|guard|interface|enum|module`.
> 
> ## Build
> 
> Run `ng build` to build the project. The build artifacts will be stored in the `dist/` directory. Use the `--prod` flag for a production build.

**Comment by burnilein** [comment]
Yes, you do get points! Good job!
