### ISSUE TITLE
Add Task Function (5)

### ISSUE THREAD

**Issue by burnilein** [codecampleipzig/communic#111]
## Add task function
- As a **team member**
- I want **add tasks**
- So that **people can do said task or join etc.**

**Comment by mmoollllee** [comment]
Hey @nlavery get +3 points if you add validation too ;)
Have a look at the RegisterCard to see how that works on form elements!

- [ ] don't forget a submit-Button as this is missing in the current state.
- [ ] Add validation
- [ ] use joined() method as used in teamTeaser Component to check if user already joined team.
