### ISSUE TITLE
Gather CSS & HTML by teams to combine and make uniform (8)

### ISSUE THREAD

**Issue by burnilein** [codecampleipzig/communic#16]
We, as a team, need to gather all the HTML and CSS and make it uniform in the end so that the app looks, works and behaves consistently. (naming conventions and let's not forget our own code)

## Acceptance Criteria:

Uniform look, behavior, classes, etc.

**Comment by mmoollllee** [comment]
Here is the first draft of the Guidlines. I feel like it should not be more! Except of some more CSS Variables and something like correct font-family for the whole projects body,...

[16-CSSGuidelines](https://github.com/codecampleipzig/communic/blob/16-CSSGuidelines/docs/CSS-Guidelines.md)
