### ISSUE TITLE
Task-list checkbox (5)

### ISSUE THREAD

**Issue by burnilein** [codecampleipzig/communic#20]
We need the checkbox in the task list to be responsive in an active state.

#### Acceptance Criteria:
- [x] Replace Checkbox in task-Component.
- [x] Change task.status & check if .status-open Class updates on the task-Component Element
- [x] Style the checkbox for different states (hover, checked, disabled) with fancy layout (Maybe ask designer)
- [x] Disable Checkbox for users that didn't join the task?

**Comment by GigaHierz** [comment]
in task-list-item-team 
in line 7, 10 change task to task.taskStatus
