### ISSUE TITLE
Create Project Service

### ISSUE THREAD

**Issue by TrizML** [codecampleipzig/communic#81]
## Project Service 
- As a **user**
- I want **to see the tasks and team members linked to a project.**
- So that **I know that those are strictly related to the project I'm in.**

**Comment by TrizML** [comment]
@gabrielheinrich Could you please explain what we need to do with that? Since you were talking about Project Service and Projects Service if I am not wrong.

**Comment by mmoollllee** [comment]
Hey there! This is done together with #72 & #20 in the branch [20-taskCheckbox](https://github.com/codecampleipzig/communic/tree/20-taskCheckbox).

Still doing the testing and maybe some comments right now.
