### ISSUE TITLE
Create Search tool in Toolbar

### ISSUE THREAD

**Issue by TrizML** [codecampleipzig/communic#88]
## Search tool in Toolbar
- As a **user**
- I want **to search for projects that match the searchTerm in their title**
- So that **in case there are many projects in Communic I can find the ones I want easily.**

Acceptance criteria:
[x] Search backend - logic:
- [x] API endpoint - /api/projects with searchTerm expected in query string of the request
Example: /api/projects?searchTerm=plan
- [x] Search should be case-insensitive
- [x] Search should support multi-word search
- [x] Search results should return default amount - Limit of 20 projects starting from the first set - Offset 0

[x] Search frontend:
- [x] Search service that will send request with searchString in query params to the backend API endpoint
- [x] SearchTool component that will represent the search input field put between <form> tags in order to use Angular's FormControl module
- [x] Once user starts typing in the search field, getResults method from Search service should be triggered to send request to the backend with the search string as query parameter
- [x] Once results are fetched from the backend, they should be displayed in a dropdown showing project title
- [x] Project title should be clickable and click on it should take the user to the Project page for the correct project
- [x] Limit the display of projects in the dropdown:
  - If <=20 projects are shown, hide "See all results link" from the bottom of the results dropdown
  - If >20 projects are shown, show "See all results" link at the bottom of the results dropdown
- [x] Click on "See all results" should take the user to Search Results page
- [x] SearchResults page that will show all matching results that the search returned
- [x] If user hits <enter> on keyboard while in search field, redirect to Search Results page
- [x] If data is still loading on Search Results page, show "Results are loading"
- [x] If there is problem related with some error returned from the backend, show "There was a problem with the backend"
- [x] If no data or error, return "Maybe your search term is incorrect?"

**Comment by simona14** [comment]
Search implemented, story description modified as per chosen implementation and acceptance criteria added.
