### ISSUE TITLE
Create Projects Service

### ISSUE THREAD

**Issue by TrizML** [codecampleipzig/communic#91]
## Create Projects Service
- As a **user**
- I want **to see all the projects available.**
- So that **I can act and join a project or check the one I want.**

## Tasks
- [x] Test
- [x] Documentation

**Comment by TrizML** [comment]
@gabrielheinrich Could you please explain what we need to do with that? Since you were talking about Project Service and Projects Service if I am not wrong.

**Comment by TrizML** [comment]
@simona14 This is your story, please update the info.

**Comment by simona14** [comment]
User Story sent for review. Changes:

- Create Projects Service to deliver data to Store to be used in components.
- Apply tests to test Projects Service methods
